version: '3.8'
services:
  api:
    build:
      context: ./OrderbookAPI
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  react:
    build:
      context: ./usdt-price-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://api:5002
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge